//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpringSiteTuner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iSpringSiteTuner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function( $ ){
        ///    $(document).ready(function() 
        ///    {
        ///		var activityActionUrl = &apos;{:siteUrl}&apos; + &apos;/activity/write&apos;
        ///		window.onbeforeunload =  function () { 
        ///			$.ajax({
        ///				type: &quot;PUT&quot;,
        ///				url: activityActionUrl,
        ///				data: {
        ///					type: &apos;Public Presentation&apos;,
        ///					subType: &apos;Close&apos;,
        ///					details: $.toJSON({
        ///						Site: window.location.href,
        ///						Name: $(&apos;head title&apos;).text()
        ///					})
        ///				},
        ///				async: false,
        ///				dataType: &apos;json&apos;
        ///			});   
        ///		};
        ///		$.ajax({
        ///			type: &quot;PUT&quot;,
        ///			url: activityA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivityFileContent {
            get {
                return ResourceManager.GetString("ActivityFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;data/jquery.js&quot;&gt;&lt;/script&gt;&lt;script src=&quot;data/json.js&quot;&gt;&lt;/script&gt;&lt;script src=&quot;data/activity.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string IndexScriptIncludePart {
            get {
                return ResourceManager.GetString("IndexScriptIncludePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.2 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.2&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\xA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JQueryFileContent {
            get {
                return ResourceManager.GetString("JQueryFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function($){var escapeable=/[&quot;\\\x00-\x1f\x7f-\x9f]/g,meta={&apos;\b&apos;:&apos;\\b&apos;,&apos;\t&apos;:&apos;\\t&apos;,&apos;\n&apos;:&apos;\\n&apos;,&apos;\f&apos;:&apos;\\f&apos;,&apos;\r&apos;:&apos;\\r&apos;,&apos;&quot;&apos;:&apos;\\&quot;&apos;,&apos;\\&apos;:&apos;\\\\&apos;};$.toJSON=typeof JSON===&apos;object&apos;&amp;&amp;JSON.stringify?JSON.stringify:function(o){if(o===null){return&apos;null&apos;;}
        ///var type=typeof o;if(type===&apos;undefined&apos;){return undefined;}
        ///if(type===&apos;number&apos;||type===&apos;boolean&apos;){return&apos;&apos;+o;}
        ///if(type===&apos;string&apos;){return $.quoteString(o);}
        ///if(type===&apos;object&apos;){if(typeof o.toJSON===&apos;function&apos;){return $.toJSON(o.toJSON());}
        ///if(o.constructor===Date){var m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSonFileContent {
            get {
                return ResourceManager.GetString("JSonFileContent", resourceCulture);
            }
        }
    }
}
