//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSpringSiteTuner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iSpringSiteTuner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function( $ ){
        ///    $(document).ready(function() 
        ///    {
        ///		var showSplash = function(){
        ///			$.metroMessageBox({
        ///				  title: &apos;{:file} ({:advertiser})&apos;, 
        ///				  content: &quot;Type your name below to open the file&quot;,
        ///				  buttons:[&quot;Click to Open&quot;],
        ///				  input: &quot;text&quot;,
        ///				  placeholder: &quot;&quot;,
        ///				  opacity: 1,
        ///				  backgroundcolor: &apos;#ffffff&apos;,
        ///				},function( action, buttom, value, selectedText ){
        ///					var userName = value;
        ///					if(userName!= &apos;&apos;)
        ///					{
        ///						window.open(&apos;public.html?User=&apos;+userName,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivityLoginFileContent {
            get {
                return ResourceManager.GetString("ActivityLoginFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function( $ ){
        ///	var getUrlParameter = function(sParam)
        ///	{
        ///		var sPageURL = window.location.search.substring(1);
        ///		var sURLVariables = sPageURL.split(&apos;&amp;&apos;);
        ///		for (var i = 0; i &lt; sURLVariables.length; i++) 
        ///		{
        ///			var sParameterName = sURLVariables[i].split(&apos;=&apos;);
        ///			if (sParameterName[0] == sParam) 
        ///			{
        ///				return decodeURI(sParameterName[1]);
        ///			}
        ///		}
        ///		return &apos;&apos;;
        ///	};     
        ///    $(document).ready(function() 
        ///    {
        ///		var user = getUrlParameter(&apos;User&apos;);
        ///		var activityActionUrl = &apos;{:siteUrl}&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivityRegularFileContent {
            get {
                return ResourceManager.GetString("ActivityRegularFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// *  Font Awesome 4.2.0 by @davegandy - http://fontawesome.io - @fontawesome
        /// *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
        /// */@font-face{font-family:&apos;FontAwesome&apos;;src:url(&apos;../fonts/fontawesome-webfont.eot?v=4.2.0&apos;);src:url(&apos;../fonts/fontawesome-webfont.eot?#iefix&amp;v=4.2.0&apos;) format(&apos;embedded-opentype&apos;),url(&apos;../fonts/fontawesome-webfont.woff?v=4.2.0&apos;) format(&apos;woff&apos;),url(&apos;../fonts/fontawesome-webfont.ttf?v=4.2.0&apos;) format(&apos;truetype&apos;),url(&apos;../fonts/fontawesome-webfont.svg?v= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FontAwesomeStyleContent {
            get {
                return ResourceManager.GetString("FontAwesomeStyleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.2 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.2&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\xA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JQueryFileContent {
            get {
                return ResourceManager.GetString("JQueryFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function($){var escapeable=/[&quot;\\\x00-\x1f\x7f-\x9f]/g,meta={&apos;\b&apos;:&apos;\\b&apos;,&apos;\t&apos;:&apos;\\t&apos;,&apos;\n&apos;:&apos;\\n&apos;,&apos;\f&apos;:&apos;\\f&apos;,&apos;\r&apos;:&apos;\\r&apos;,&apos;&quot;&apos;:&apos;\\&quot;&apos;,&apos;\\&apos;:&apos;\\\\&apos;};$.toJSON=typeof JSON===&apos;object&apos;&amp;&amp;JSON.stringify?JSON.stringify:function(o){if(o===null){return&apos;null&apos;;}
        ///var type=typeof o;if(type===&apos;undefined&apos;){return undefined;}
        ///if(type===&apos;number&apos;||type===&apos;boolean&apos;){return&apos;&apos;+o;}
        ///if(type===&apos;string&apos;){return $.quoteString(o);}
        ///if(type===&apos;object&apos;){if(typeof o.toJSON===&apos;function&apos;){return $.toJSON(o.toJSON());}
        ///if(o.constructor===Date){var m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSonFileContent {
            get {
                return ResourceManager.GetString("JSonFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;data/metro-notification.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;data/font-awesome.css&quot;&gt;
        ///		&lt;script src=&quot;data/jquery.js&quot;&gt;&lt;/script&gt;
        ///		&lt;script src=&quot;data/json.js&quot;&gt;&lt;/script&gt;
        ///		&lt;script src=&quot;data/metro-notification.js&quot;&gt;&lt;/script&gt;
        ///		&lt;script src=&quot;data/activity-login.js&quot;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string LoginIndexFileContent {
            get {
                return ResourceManager.GetString("LoginIndexFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function($){(window._gsQueue||(window._gsQueue=[])).push(function(){_gsDefine(&quot;plugins.CSSPlugin&quot;,[&quot;plugins.TweenPlugin&quot;,&quot;TweenLite&quot;],function(a){var d,e,f,g,c=function(){a.call(this,&quot;css&quot;),this._overwriteProps.length=0},h={},i=c.prototype=new a(&quot;css&quot;);i.constructor=c,c.version=&quot;1.8.0&quot;,c.API=2,c.defaultTransformPerspective=0,i=&quot;px&quot;,c.suffixMap={top:i,right:i,bottom:i,left:i,width:i,height:i,fontSize:i,padding:i,margin:i,perspective:i};var G,H,I,J,K,L,j=/(?:\d|\-\d|\.\d|\-\.\d)+/g,k=/(?:\d|\-\d|\.\d|\-\.\d| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetroNotificationScriptFileContent {
            get {
                return ResourceManager.GetString("MetroNotificationScriptFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #mnSBcontainerTR{position:fixed;z-index:9999;top:10px;right:0}#mnSBcontainerTL{position:fixed;z-index:9999;top:10px;left:0}#mnSBcontainerBL{position:fixed;z-index:9999;bottom:10px;left:0}#mnSBcontainerBR{position:fixed;z-index:9999;bottom:10px;right:0}.mnSmallBox{font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif!important;position:relative;margin-bottom:10px;color:white;opacity:0;cursor:pointer;line-height:0}.mnSmallBox table{width:100%!important;height:100%!important;border:0!important;border-spacing [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetroNotificationStyleFileContent {
            get {
                return ResourceManager.GetString("MetroNotificationStyleFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;data/jquery.js&quot;&gt;&lt;/script&gt;&lt;script src=&quot;data/json.js&quot;&gt;&lt;/script&gt;&lt;script src=&quot;data/activity-regular.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string PublicIndexScriptIncludePart {
            get {
                return ResourceManager.GetString("PublicIndexScriptIncludePart", resourceCulture);
            }
        }
    }
}
